### ISSUE TITLE
I will reconstruct lua.js very soon.

### ISSUE THREAD

**Issue by tdzl2003** [tdzl2003/lua.js#18]
Target:

1. Build with CommonJS, compatible with node.js/webpack/react native
2. Solve upvalue-in-repeat issue. This breaks many people to use lua.js
3. Performance improve because my JS level was up.
4. Support missing grammar,  hex integer etc..
5. Unit Test, Travis-CI, blah blah..

**Comment by upupzealot** [comment]
glad to here that, would it be a new project?

**Comment by tdzl2003** [comment]
No, all will be in this repo.
