### ISSUE TITLE
请提供源码

### ISSUE THREAD

**Issue by vincentlui** [tdzl2003/lua.js#3]
非压缩版

**Comment by tdzl2003** [comment]
您好，lua.js可以免费使用，但暂时未确定开源。有需要请联系QQ:402740419或邮箱：tdzl2003@gmail.com

有任何功能上的需求也可以直接使用github的issue功能提交。

感谢您对lua.js的关注。

**Comment by tdzl2003** [comment]
Hi,everyone, Lua.js is now open source. Be free to use it!
