### ISSUE TITLE
can this compile to readable js code

### ISSUE THREAD

**Issue by walter211** [tdzl2003/lua.js#5]
I am going to use this to convert a lua project to web+js application. Because of I am using the 3rd party framework I may need add more function according the framework's api, so is there any method to get this doen or any suggestion will be really appreciated, thanks.

**Comment by tdzl2003** [comment]
You can use javascript library directly via lua.js. See this sample:

[http://luajs.org/demos/jquery/index.html](http://luajs.org/demos/jquery/index.html)
