### ISSUE TITLE
`require` does not add the exported variable name to the global context

### ISSUE THREAD

**Issue by brollb** [tdzl2003/lua.js#8]
when using `require`, it should assign the imported value to the name of the exported variable in the current context

**Comment by tdzl2003** [comment]
I think this is not right. [See document here.](https://www.lua.org/manual/5.2/manual.html#pdf-require)

If you require a module in lua, it will not be in _G. Only the build-in package is also assigned to _G.

You can try this on original lua:

```lua
package.preload['foo'] = function ()
  return {bar = 1}
end

local foo = require('foo')

console.log(foo)
console.log(_G.foo)
```

**Comment by brollb** [comment]
I may not have explained it the best. The issue can be reproduced with the following files:

The main file:
```lua
-- require a library and verify some value
test = require './example'
assert(test == 1)

-- should add the exported variable to current context
assert(abc == 1)
```

the dependency (`example.lua` in the same directory):
```lua
abc = 1
return abc
```

Running the main file using `lua` will terminate with no error. However, running the file using lua.js causes the second assert to fail.

If you don't mind checking out my fork, this can be quickly replicated by running [require.spec.lua](https://github.com/brollb/lua.js/blob/8-require-add-variable/test/test-cases/require.spec.lua) with lua then running `npm test`

**Comment by tdzl2003** [comment]
I read your code. You create a new context for each file, that's why thing goes wrong.

You should use only one context if you want to access same _G between files. I'll give a PR for you.

**Comment by brollb** [comment]
Thanks again for the PR!
